# Generated by Django 5.1.2 on 2024-11-26 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_employee_security_answer_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='security_answer_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='security_answer_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='security_answer_3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='security_question_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='security_question_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='security_question_3',
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
