# Generated by Django 5.1.2 on 2025-01-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250116_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.RemoveField(
            model_name='eventreservation',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
