# Generated by Django 5.1.2 on 2025-01-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
    ]
