# Generated by Django 5.1.2 on 2025-01-16 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_description_survey_additional_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dineinreservation',
            name='parking_slots_needed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dineinreservation',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dineinreservation',
            name='advance_order',
            field=models.JSONField(blank=True, help_text="Stores details of advance orders as JSON (e.g., [{'product_id': '123', 'quantity': 2}])", null=True),
        ),
        migrations.AlterField(
            model_name='dineinreservation',
            name='preferred_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.diningarea'),
        ),
    ]
