# Generated by Django 5.1.2 on 2025-01-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20250117_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinreservation',
            name='advance_order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dineinreservation',
            unique_together={('customer', 'reservation_date', 'reservation_time')},
        ),
    ]
