# Generated by Django 5.1.2 on 2025-01-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_dineinreservation_advance_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineinreservation',
            name='reference_number',
            field=models.CharField(default='DEFAULT_REF_NUMBER', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='eventreservation',
            name='reference_number',
            field=models.CharField(default='DEFAULT_REF_NUMBER', max_length=50, unique=True),
        ),
    ]
