# Generated by Django 5.1.2 on 2025-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dineinreservation_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinreservation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventreservation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
