# Generated by Django 5.1.2 on 2025-01-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20250125_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinreservation',
            name='reference_number',
            field=models.CharField(default='DEFAULT_REF_NUMBER', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='eventreservation',
            name='reference_number',
            field=models.CharField(default='DEFAULT_REF_NUMBER', max_length=50, unique=True),
        ),
    ]
