# Generated by Django 5.1.2 on 2025-01-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_dineinreservation_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
