# Generated by Django 5.1.2 on 2025-01-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_eventreservation_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreservation',
            name='total_cost',
        ),
    ]
