# Generated by Django 5.1.2 on 2025-01-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_eventreservation_total_cost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dineinreservation',
            unique_together={('reservation_date', 'reservation_time', 'preferred_area')},
        ),
    ]
