# Generated by Django 5.1.2 on 2025-01-28 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_dineinreservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinreservation',
            name='reference_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
