# Generated by Django 5.1.2 on 2025-01-28 19:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_dineinreservation_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dineinreservation',
            name='advance_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dineinreservation',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('grab_pay', 'GrabPay'), ('card', 'Card'), ('qrph', 'QRPH'), ('brankas_bdo', 'Brankas BDO'), ('brankas_landbank', 'Brankas Landbank'), ('paymaya', 'PayMaya')], default='card', max_length=50),
        ),
        migrations.AlterField(
            model_name='dineinreservation',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference_number, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='eventreservation',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('grab_pay', 'GrabPay'), ('card', 'Card'), ('qrph', 'QRPH'), ('brankas_bdo', 'Brankas BDO'), ('brankas_landbank', 'Brankas Landbank'), ('paymaya', 'PayMaya')], default='card', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventreservation',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference_number, max_length=50, unique=True),
        ),
    ]
