# Generated by Django 5.1.2 on 2025-01-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_customer_email_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dineinreservation',
            unique_together=set(),
        ),
    ]
