# Generated by Django 5.1.2 on 2025-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_dineinreservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='reservation_date',
            field=models.DateField(unique=True),
        ),
    ]
