# Generated by Django 5.1.2 on 2025-01-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_eventreservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
