# Generated by Django 5.1.2 on 2025-02-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_eventreservation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('grab_pay', 'GrabPay'), ('card', 'Card'), ('qrph', 'QRPH'), ('brankas_bdo', 'Brankas BDO'), ('brankas_landbank', 'Brankas Landbank'), ('paymaya', 'PayMaya')], max_length=50, null=True),
        ),
    ]
