# Generated by Django 5.1.2 on 2025-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_eventreservation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('grab_pay', 'GrabPay'), ('card', 'Card'), ('qrph', 'QRPH'), ('brankas_bdo', 'Brankas BDO'), ('brankas_landbank', 'Brankas Landbank'), ('paymaya', 'PayMaya')], default='card', max_length=50),
        ),
    ]
