# Generated by Django 5.1.2 on 2025-02-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_eventreservation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='payment_method',
            field=models.CharField(choices=[('none', 'None'), ('gcash', 'Gcash'), ('grab_pay', 'Grab Pay'), ('card', 'Card'), ('qrph', 'QRPH'), ('brankas_bdo', 'Brankas BDO'), ('brankas_landbank', 'Brankas Landbank'), ('paymaya', 'Paymaya')], default='none', max_length=50),
        ),
    ]
