# Generated by Django 5.1.2 on 2025-02-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_dineinreservation_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreservation',
            name='event_date_time',
        ),
    ]
