# Generated by Django 5.1.2 on 2025-02-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_eventreservation_event_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservation',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Overdue', 'Overdue')], default='Confirmed', max_length=50),
        ),
    ]
