# Generated by Django 5.1.2 on 2025-02-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_visitorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorlog',
            old_name='timestamp',
            new_name='visit_time',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='user_agent',
        ),
    ]
