# Generated by Django 5.1.2 on 2025-02-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_timestamp_visitorlog_visit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
    ]
