# Generated by Django 5.1.2 on 2025-03-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_customer_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(db_index=True, max_length=255),
        ),
    ]
